package Demo;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package main.java.Demo;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
//@Test public void testBk(){}

}
